Resources:
  TeamsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Teams
      AttributeDefinitions:
        - AttributeName: teamId
          AttributeType: S
      KeySchema:
        - AttributeName: teamId
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST